version: '3'
services:
  webserver:
    build:
      context: ./bin/apache
    container_name: apache2.4-php7.3
    restart: always
    ports:
      - '${HTTP_PORT}:80'
      - '${HTTPS_PORT}:443'
    links:
      - mysql
      - redis
    volumes:
      - '${HTTPD_DOCUMENT_ROOT-./www}:/var/www'
      - '${HTTPD_VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled'
      - '${HTTPD_PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini'
      - '${HTTPD_LOG_DIR-./logs/apache}:/var/log/apache2'
  mysql:
    build:
      context: './bin/${DATABASE}'
    container_name: '${DATABASE}'
    restart: always
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - '${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql'
      - '${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql'
      - '${MYSQL_MY_CNF-./config/mysql/my.cnf}:/etc/mysql/my.cnf'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_SAMPLE_DATABASE}'
      MYSQL_USER: '${MYSQL_SAMPLE_USERNAME}'
      MYSQL_PASSWORD: '${MYSQL_SAMPLE_PASSWORD}'
  phpmyadmin:
    build:
      context: ./bin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: '${MYSQL_PORT}'
      PMA_USER: '${MYSQL_ROOT_USER}'
      PMA_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_USER: '${MYSQL_SAMPLE_USERNAME}'
      MYSQL_PASSWORD: '${MYSQL_SAMPLE_PASSWORD}'
    ports:
      - '${PMA_PORT}:80'
    volumes:
      - /sessions
  redis:
    build:
      context: ./bin/redis
    container_name: redis
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
